### ISSUE TITLE
Missing utils.js

### ISSUE THREAD

**Issue by confuser** [royriojas/flat-cache#9]
v1.2.0 only includes cache.js as stated in package.json. Causing problems with ESLint.

```
> eslint --format=node_modules/eslint-formatter-pretty .

Cannot find module './utils'
Error: Cannot find module './utils'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/private/var/app/v1-customers/node_modules/eslint/node_modules/file-entry-cache/node_modules/flat-cache/cache.js:4:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

**Comment by leizongmin** [comment]
Met the same problem. The author was published a new version v1.2.1 and resoved this problem. Hehe

**Comment by royriojas** [comment]
Hi @confuser, @leizongmin 

Sorry for the broken publish, v1.2.1 fixed the problem as @leizongmin correctly mention.

**Comment by royriojas** [comment]
duplicates #8
